version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - ./reports:/app/reports
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=socialmetrics
      - MYSQL_PASSWORD=socialmetrics
      - MYSQL_DATABASE=socialmetrics
      - MYSQL_PORT=3307
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=socialmetrics
      - MYSQL_USER=socialmetrics
      - MYSQL_PASSWORD=socialmetrics
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 